---
name: "pipeline-components-ruff"
description: "ruff by Pipeline Components"
author: "Robbert Müller <spam.me@grols.ch>"
branding:
  icon: "flag"
  color: "green"
inputs:
  directory:
    description: "Directory to lint"
    required: false
    default: .
  options:
    description: "Additional options"
    required: false
    default: ""
runs:
  using: "docker"
  image: docker://pipelinecomponents/ruff
  args:
    - ruff
    - --format=gitlab
    - "${{ inputs.options }}"
    - "${{ inputs.directory }}"
